const htmlWords = [
    "HyperText Markup Language",
    "<body>",
    "block-elements",
    "inline-elements",
    "<p>",
    "<div>",
    "Ordered List",
    "<ol>",
    "Unordered List",
    "<ul>",
    "<article>",
    "List items",
    "<li>",
    "<button>",
    "<h1>",
    "<script>",
    "<span>",
    "<br>",
    "<a>",
    "<footer>",
    "<header>",
    "<nav>",
    "<canvas>",
    "Cascading Style Sheets",
    "align-content",
    "align-self",
    "background",
    "background-repeat",
    "border",
    "flex",
    "flex-wrap",
    "font-family",
    "font-weight",
    "grid",
    "height",
    "width",
    "justify-content",
    "margin",
    "padding",
    "quotes",
    "text-align",
    "text-transform",
    "Bootstrap",
    "background",
    "visibility",
    "display",
    "lightweight",
    "interpretable",
    "first-class functions",
    "const",
    "let",
    "constructor",
    "console.log()",
    "declare",
    "initialize",
    "primitive values",
    "number",
    "string",
    "boolean",
    "null",
    "undefined",
    "symbol",
    " * + - /",
    "module %",
    "if-else",
    "PEMDAS((),**,*,/,+,-)",
    "non-primitive",
    "backticks",
    ".indexOf(substr)",
    ".slice()",
    "key-value pair",
    "object",
    "array",
    "object-oriented programming",
    "&& and",
    "|| or",
    "!truthieToFalsie",
    "camelCase",
    "function-statement",
    "arrow-function",
    "object-literals",
    ".querySelector()",
    "node",
    "nodeList",
    "…Spread Operator",
    ".forEach()",
    ".map()",
    "setInterval()",
    "callback",
    "mutate",
    ".reverse()",
    "API",
    "context",
    "scope",
    "this.",
]




